### DISCUSSION TITLE
support for autolinks

### DISCUSSION THREAD

**Discussion by electriquo** [repository-settings/app#479] [API support]
Github introduced [APIs for Autolinks](https://github.blog/changelog/2021-08-02-apis-for-autolinks/) and the [API has support for it](https://docs.github.com/en/rest/reference/repos#autolinks).

what do you think about supporting it?

Something as follows should due

```yaml
# Create an autolink reference for a repository
autolinks:
  # Required. The prefix appended by a number will generate a link any time it is found in an issue, pull request, or commit.
  key_prefix:
  # Required. The URL must contain for the reference number.
  url_template: 
```

Probably a new plugin can handle this
https://github.com/probot/settings/blob/54668ca6549006ffb5e80a71da8ed3beb2777edc/lib/settings.js#L25-L32
