### ISSUE TITLE
Allow setting environment reviewers using team slugs or usernames

### ISSUE THREAD

**Issue by gavinclarkeuk** [repository-settings/app#1109]
## New Feature

Settings app supports setting environment reviewers by specifying the team or user id, however the id's aren't easily accessible through the GitHub UI. It also isn't very intuitive for human reviewers of the `settings.yml` file.

It would be much clearer to also allow setting environment reviewers by team slug/username. e.g.

```yaml

environments:
  my-env:
    reviewers:
      - slug: gavinclarkeuk
        type: User
      - slug: @my-org/my-team
        type: Team
```

(Not sure it the type attribute would be required, or if it could be inferred)
