### ISSUE TITLE
Override parameter of an inherited settings file

### ISSUE THREAD

**Issue by possani** [repository-settings/app#488]
## Description

Dear maintainers,

I'm having a little trouble trying to override a specific parameter (contexts) of an inherited settings file.

### Original File

```
# tf-settings/.github/settings.yml

...
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions: {}
      required_status_checks:
        strict: true
        contexts: ["atlantis/plan"]
      enforce_admins: null
      required_linear_history: false
      restrictions: null
```

### Test Repository File

```
# tf-test-module/.github/settings.yml

_extends: tf-settings:.github/settings.yml

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts: null
```

## Notes

I tried setting it to an _empty array_ and to _null_ but it didn't work.

Does the [second note](https://github.com/probot/settings#notes) also applies when overriding an existing config file?
