### ISSUE TITLE
Question: How to configure organization-wide settings using the .github repository?

### ISSUE THREAD

**Issue by dgokcin** [repository-settings/app#654]
Hello

I would like to ask what is the best way of configuring some settings organization-wide and extending it for repositories. If I create a .github repository in my organization and only add the settings.yml file with only the following config, would a repository that DOES NOT have a settings.yml file in its .github directory have the fix label or it needs to have a settings.yml file which will only have a  `_extends: .github` inside? Any help is appreciated. 

Thanks
```
labels:
  - name: fix
    color: '#E1A296'
    description: A label used to mark fixes for automatic release notes generation.

```
