### ISSUE TITLE
[bug] labels donot work

### ISSUE THREAD

**Issue by Alice52** [repository-settings/app#678]
### What is actually happening

1. I create a repo, named `.github`
2. add `settings.yml` in `.github/`

```yml
Labels: define labels for Issues and Pull Requests
labels:

  - name: github
    color: '#367F46'

```

3. I install `Settings` app for all repoes.

### What is the expected behavior

1. I should be able to choose this labels in repo issue.
2. But I cannot get this label in repo's issue

### Error output, if available

- N/A
```

```

### Are you using the hosted instance of repository-settings/app or running your own?

- N

#### Version of repository-settings/app

- Latest version
