### ISSUE TITLE
Support variables in environments

### ISSUE THREAD

**Issue by rlmartin** [repository-settings/app#711]
## Prerequisites:

* Is the functionality available in the GitHub UI? If so, please provide a link to information about the feature.
[Documentation of the feature](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#environment-variables)
[How it can be used in GitHub Actions](https://docs.github.com/en/actions/learn-github-actions/variables)
![Screenshot 2023-02-23 at 1 08 22 PM](https://user-images.githubusercontent.com/1110255/220992938-8892c4aa-f78f-48f6-b2df-d89cef506599.png)

* Is the functionality available through the GitHub API? If the functionality is available, please provide links to the
  API documentation (https://developer.github.com/v3/) as well as the Octokit documentation (https://octokit.github.io/).
[Documentation of the feature in the API](https://docs.github.com/en/rest/actions/variables?apiVersion=2022-11-28#create-an-environment-variable)

* If the functionality is not yet available in the API, it would be helpful if you
  contacted support (https://support.github.com/) or posted in the Community Forum (https://github.community/). Please
  include a link to the forum post if you create one or a copy of the response from support.
N/A

## New Feature

Please describe the desired new functionality:
Under the `environments` section, add a `vars` section that is a map of `var name` => `var value`. Example:

```
environments:
  - name: production
    vars:
      AWS_DEPLOYMENT_ROLE: arn:aws:iam::0000000000:role/deployment-role
  - name: development
    vars:
      AWS_DEPLOYMENT_ROLE: arn:aws:iam::1111111111:role/deployment-role
```
