### ISSUE TITLE
Extend environment settings to support prevent_self_review parameter

### ISSUE THREAD

**Issue by brockgwex** [repository-settings/app#931]
## Prerequisites:

* Is the functionality available in the GitHub UI? If so, please provide a link to information about the feature.
https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#:~:text=prevent%20self%2Dreviews

* Is the functionality available through the GitHub API? If the functionality is available, please provide links to the
  API documentation (https://developer.github.com/v3/) as well as the Octokit documentation (https://octokit.github.io/).
https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#:~:text=prevent%20self%2Dreviews

## New Feature

Adds the ability to control whether `prevent_self_review` is enabled or disabled for a given deployment environment.

```
environments:
  - name: prod
    reviewers:
      - id: 5847163
        type: 'Team'
    prevent_self_review: true
    deployment_branch_policy:
      protected_branches: true
```
