### ISSUE TITLE
optional branch protection settings

### ISSUE THREAD

**Issue by omercnet** [repository-settings/app#967]
I wish to have an org wide branch protection rules, requiring all repos to have basic branch protection, it would ideally look something like this:

```yaml
branches:
  - name: master
    # Branch Protection settings. Set to null to disable
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      enforce_admins: true
      required_linear_history: true
```

but based on https://github.com/repository-settings/app/issues/150 this won't be applied because some settings are missing, specifically the `required_status_checks` setting.

my ask is, that missing settings will simply be ignored or patched to existing settings, so by settings this at the org level, it would allow customizing checks for each repo but not removing the org level requirements of reviews, enforce admins, etc.
